version: "3"
services:
  postgresdb:
    container_name: postgresdb
    image: library/postgres:14.4
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgresdb
    ports:
      - 5432:5432